spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug